aws_region            = "us-east-1"
environment           = "production"
project_name          = "ticketer"
instance_type         = "t3.small"
key_name              = "devopsassignment"
mongodb_root_password = "bo27JjkSWPuWIH7OJd5+T8cDKAxy9fzC951Qm6Bb8rg="
session_secret        = "FYwbQKPcAQ3PBrLYXfFbIKomzLTPN2GGyuMj7YCrGcA="
